application: georgebuffer2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /libs
  static_dir: bower_components

- url: /static
  static_dir: george/static


- url: /sandbox
  script: sandbox.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: latest
- name: lxml
  version: "latest"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.(rb|scss|sass|less|DS_Store|zip|log)$
- ^local_settings.pyc?$
- ^(.*/)(docs|benchmarks|example_project)/.*
- ^htmlcov/.*
- ^google/.*
- ^google_appengine/.*
- ^node_modules/.*
- ^bower_components/.*
- ^apps/.*
- ^lib/google-cloud-datastore-orm/.*
- ^bulkloader.*
